Repository emeth-defi-automation/portfolio-management-platform, pull requests merged in 2024-05, with the labels that each got.

#176 Feature 170/frontend add swap
  src/abi/emethContractAbi.ts
  src/components/Forms/CoinsToApprove.tsx
  src/components/Groups/Group.tsx
  src/components/Groups/TokenRow.tsx
  src/database/tokens.ts
  src/routes/app/portfolio/index.tsx
  src/utils/tokens/swap.tsx
Labels: bug, enhancement

#187 Fixed problem with adding existing wallet for the second time.
  src/components/Forms/AddWalletFormFields.tsx
  src/routes/app/wallets/index.tsx
  src/routes/app/wallets/interface.ts
  src/routes/app/wallets/server/addWalletAction.ts
  src/utils/validators/addWallet.ts
Labels: fix

#192 Fix for batch transfers with no subportfolio/subportfolio with no exe wallet
  src/components/Forms/portfolioTransfters/CoinsToTransfer.tsx
  src/interface/structure/Structure.ts
  src/routes/app/portfolio/index.tsx
  src/utils/validators/availableStructure.ts
Labels: bug

#210 Newly opened modals have first input field in focus
  src/components/Forms/AddWalletFormFields.tsx
  src/components/Input/Input.tsx
  src/components/Modal/Modal.tsx
  src/routes/app/portfolio/index.tsx
Labels: bug

#205 New Structure Modal Validation
  src/routes/app/portfolio/index.tsx
  src/utils/validators/addWallet.ts
  src/utils/validators/availableStructure.ts
Labels: bug
